### ISSUE TITLE
"flag provided but not defined: -auth" when running the Docker image

### ISSUE THREAD

**Issue by Kovah** [baethon/docker-goatcounter#1]
When running the image, I get the following errors:
```
$ docker run --name goatcounter \
  -e GOATCOUNTER_DOMAIN=stats.domain.com \
  -e GOATCOUNTER_EMAIL=admin@domain.com \
  baethon/goatcounter

goatcounter_1  | flag provided but not defined: -auth
goatcounter_1  | flag provided but not defined: -auth
```
The Docker image works correctly when the 1.4 tag is defined:
```
docker run --name goatcounter \
  -e GOATCOUNTER_DOMAIN=stats.domain.com \
  -e GOATCOUNTER_EMAIL=admin@domain.com \
  baethon/goatcounter:1.4
```

**Comment by radmen** [comment]
@Kovah thanks for the report. Did you try to pull latest version of the `baethon/goatcounter:latest`?

**Comment by Kovah** [comment]
Yes. I used the :latest image first, based on [11fa7286f0aa](https://hub.docker.com/layers/baethon/goatcounter/latest/images/sha256-11fa7286f0aa4a9a49f58a3e4611c677bcbafe0ae39e5a168e35a1ceb518ce93?context=explore)

**Comment by radmen** [comment]
@Kovah I've pushed the fix. Build is on the way.
