### ISSUE TITLE
version 2.x

### ISSUE THREAD

**Issue by felixsanz** [baethon/docker-goatcounter#4]
can you bump to 2.x ? also... this image seems to not work anymore

**Comment by radmen** [comment]
@felixsanz I'm not using this actively, but will see what I can do.

> also... this image seems to not work anymore

What do you mean? You should be able to download it w/o issues from Docker Hub.

**Comment by felixsanz** [comment]
it's broken, doesn't work. you are cloning like this `RUN git clone https://github.com/zgoat/goatcounter.git`

it's cloning 2.x and doesn't work with your setup/dockerfile

**Comment by radmen** [comment]
Ok, so the Dockerfile is not working? I've added `v2.0` (be80ee420e6807dc893da2ad15b87dea33755f3a) and pushed the image to Docker Hub.

Checking now if the `latest` image builds correctly.
